# fly.toml app configuration file generated for wp-mysql-little-sound-540 on 2025-09-30T17:30:13+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wp-mysql-little-sound-540'
primary_region = 'cdg'

[build]
  image = 'mariadb'

[[mounts]]
  source = 'mysqldata'
  destination = '/var/lib/mysql'

[http_service]
  internal_port = 3306
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

 

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "30s"