# fly.toml app configuration file generated for app-dry-field-6207 on 2025-09-30T17:40:08+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'app-dry-field-6207'
primary_region = 'cdg'

[build]
  image = 'wordpress'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  WORDPRESS_DB_HOST = "wp-mysql-little-sound-540.internal:3306"
  WORDPRESS_DB_NAME = "wordpress_bd"
  WORDPRESS_TABLE_PREFIX = "wp_"
  WORDPRESS_DEBUG = "false"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
